# Generated by Django 5.1.15 on 2026-04-16 05:57

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queue_number', models.IntegerField()),
                ('queue_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('serving', 'Serving'), ('done', 'Done'), ('skipped', 'Skipped')], default='waiting', max_length=20)),
                ('source', models.CharField(choices=[('walkin', 'Walk-in'), ('whatsapp', 'WhatsApp'), ('online', 'Online')], default='walkin', max_length=20)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('serving_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='clinics.clinic')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
            ],
            options={
                'db_table': 'queue_queueentry',
                'ordering': ['queue_number'],
                'unique_together': {('clinic', 'queue_date', 'queue_number')},
            },
        ),
    ]
