# Generated by Django 5.1.15 on 2026-04-16 05:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('total_consultation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_procedures', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_drugs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('qris', 'QRIS'), ('virtual_account', 'Virtual Account'), ('free', 'Free')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('midtrans_order_id', models.CharField(blank=True, max_length=100)),
                ('midtrans_transaction_id', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.CharField(blank=True, max_length=500)),
                ('cashier_notes', models.TextField(blank=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clinics.clinic')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='emr.visit')),
            ],
            options={
                'db_table': 'billing_invoice',
                'ordering': ['-created_at'],
            },
        ),
    ]
