# Generated by Django 5.1.15 on 2026-04-16 05:57

import apps.core.encryption
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('inventory', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ICD10Code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('description_en', models.CharField(max_length=500)),
                ('description_id', models.CharField(blank=True, max_length=500)),
                ('chapter', models.CharField(blank=True, max_length=10)),
                ('block', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(blank=True, max_length=10)),
                ('is_billable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'emr_icd10code',
            },
        ),
        migrations.CreateModel(
            name='EMRTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('template_subjective', models.TextField(blank=True)),
                ('template_objective', models.TextField(blank=True)),
                ('template_assessment', models.TextField(blank=True)),
                ('template_plan', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emr_templates', to='clinics.clinic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emr_emrtemplate',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('chief_complaint', apps.core.encryption.EncryptedTextField(blank=True, null=True)),
                ('soap_subjective', apps.core.encryption.EncryptedTextField(blank=True, null=True)),
                ('soap_objective', apps.core.encryption.EncryptedTextField(blank=True, null=True)),
                ('soap_assessment_notes', apps.core.encryption.EncryptedTextField(blank=True, null=True)),
                ('soap_plan_notes', apps.core.encryption.EncryptedTextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('satusehat_encounter_id', models.CharField(blank=True, max_length=100)),
                ('last_autosave', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
            ],
            options={
                'db_table': 'emr_visit',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('dosage_instruction', models.TextField()),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.drug')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='emr.visit')),
            ],
            options={
                'db_table': 'emr_prescription',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icd10_code', models.CharField(max_length=10)),
                ('icd10_description_en', models.CharField(blank=True, max_length=500)),
                ('icd10_description_id', models.CharField(blank=True, max_length=500)),
                ('is_primary', models.BooleanField(default=False)),
                ('clinical_notes', models.TextField(blank=True)),
                ('satusehat_condition_id', models.CharField(blank=True, max_length=100)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='emr.visit')),
            ],
            options={
                'db_table': 'emr_diagnosis',
            },
        ),
    ]
