# Generated by Django 5.1.15 on 2026-04-16 05:57

import apps.core.encryption
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('subscription_plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('plus', 'Plus')], default='starter', max_length=20)),
                ('satusehat_client_id', apps.core.encryption.EncryptedCharField(blank=True, max_length=200, null=True)),
                ('satusehat_client_secret', apps.core.encryption.EncryptedCharField(blank=True, max_length=200, null=True)),
                ('satusehat_org_id', models.CharField(blank=True, max_length=100)),
                ('whatsapp_phone_number_id', models.CharField(blank=True, max_length=100)),
                ('whatsapp_access_token', apps.core.encryption.EncryptedCharField(blank=True, max_length=500, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic',
                'verbose_name_plural': 'Clinics',
                'db_table': 'clinics_clinic',
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_patients', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinics_doctorschedule',
                'unique_together': {('clinic', 'doctor', 'day_of_week')},
            },
        ),
    ]
