# Generated by Django 5.1.15 on 2026-04-16 05:57

import apps.core.encryption
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_record_number', models.CharField(db_index=True, max_length=20)),
                ('nik', apps.core.encryption.EncryptedCharField(blank=True, max_length=16, null=True)),
                ('name', apps.core.encryption.EncryptedCharField(max_length=255)),
                ('name_search', models.CharField(blank=True, db_index=True, max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('blood_type', models.CharField(blank=True, max_length=5)),
                ('allergy_notes', models.TextField(blank=True)),
                ('satusehat_patient_id', models.CharField(blank=True, max_length=100)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='clinics.clinic')),
            ],
            options={
                'db_table': 'patients_patient',
                'ordering': ['name_search'],
                'unique_together': {('clinic', 'medical_record_number')},
            },
        ),
    ]
