# Generated by Django 5.1.15 on 2026-04-16 05:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(max_length=50)),
                ('local_id', models.CharField(db_index=True, max_length=100)),
                ('satusehat_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='clinics.clinic')),
            ],
            options={
                'db_table': 'satusehat_synclog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'status'], name='satusehat_s_clinic__044d4e_idx'), models.Index(fields=['resource_type', 'local_id'], name='satusehat_s_resourc_3ad2f1_idx')],
            },
        ),
    ]
